version: '3.8'
name: expense_crud
services:
    api:
        container_name: expense_api
        image: expense_api:latest
        environment:
            - ASPNETCORE_ENVIRONMENT=docker
            - ASPNETCORE_URLS=http://+:80
        ports:
          - 80:80
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        container_name: dev
        image: postgres
        environment:
          - POSTGRES_USER=appuser
          - POSTGRES_PASSWORD=secret
        ports:
          - 5432:5432
        volumes:
          - postgres-data:/data/db
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U admin"]
          interval: 10s
          timeout: 5s
          retries: 5
volumes:
  postgres-data: