version: '3.8'
name: expense-api
services:
    api:
        container_name: product-api
        image: products-crud-api:latest
        environment:
            - ASPNETCORE_ENVIRONMENT=docker
            - ASPNETCORE_URLS=http://+:80
        ports:
          - 80:80
        depends_on:
            postgres:
                condition: service_healthy
    sqlite:
        container_name: sqlite
        image: sqlite:15-alpine
        volumes:
          - sqlite-data:/data/db
volumes:
  postgres-data: